version: '3.8'

services:
  frontend:
    build: .
    container_name: meta-fav-frontend
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=production
    command: serve -s build -l 4173