import { tabClasses } from '@mui/joy/Tab';

export const styles = {
  rootBox: {
    bgcolor: 'background.body',
    height: '100%',
    width: '100%',
    color: 'text.primary',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    p: 2,
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  containerBox: {
    width: '100%',
    maxWidth: '800px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    mt: 4,
    mx: 'auto',
    overflow: 'auto',
  },
  title: {
    mb: 2,
    textAlign: 'center',
  },
  tabs: {
    bgcolor: 'transparent',
    mx: 'auto',
  },
  tabList: (tabIndex, slideIn) => ({
    position: 'relative',
    p: 0.5,
    gap: 0.5,
    borderRadius: 'xl',
    bgcolor: 'background.level2',
    display: 'inline-flex',
    justifyContent: 'center',
    width: 'auto',
    mx: 'auto',
    overflow: 'hidden',
    [`& .${tabClasses.root}[aria-selected="true"]`]: {
      bgcolor: 'transparent',
      transition: 'all 0.2s ease',
    },
    [`& .${tabClasses.root}`]: {
      px: 2,
      py: 1,
      minHeight: 36,
      width: 100,
      fontSize: 'sm',
      transition: 'all 0.2s ease',
      zIndex: 1,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    '&::before': {
      content: '""',
      position: 'absolute',
      height: 'calc(95% - 5px)',
      width: 100,
      top: '4px',
      left: tabIndex === 0 ? '4px' : 'calc(100px + 8px)',
      transform: 'none',
      bgcolor: 'background.surface',
      borderRadius: 'lg',
      transition: 'all 0.3s ease',
      animation: `${slideIn} 0.3s ease-out`,
      zIndex: 0,
    },
  }),
  contentBox: {
    mt: 2,
    width: '100%',
    mx: 'auto',
  },
}; 